### ISSUE TITLE
Researcher lavish

### ISSUE THREAD

**Issue by BoboMcFrenzy** [Storm-Veil-Gaming/Storm-Veil-Modding#21]
Advanced Upgrade 3 - Lavish/Upgrades still not affect the culinary papers
Advanced Upgrade 2 - Advance upgrade 1 is getting affected by it
Engineer Resarch Paper Modern - Paper instead of Ink is affected

**Comment by BoboMcFrenzy** [comment]
MadScience Book - Advanced Upgrades probably affected, can't check at the moment since no Lab yet

**Comment by BoboMcFrenzy** [comment]
After playing with it a while now, i think paper in the recipes should be affected. It's absurd how much fiber needs to be processed for al the papers that are needed, especially now that we make scrolls and not books anymore.

**Comment by primo4e** [comment]
fair
