### ISSUE TITLE
Animal Husbandry

### ISSUE THREAD

**Issue by BoboMcFrenzy** [Storm-Veil-Gaming/Storm-Veil-Modding#24]
The recipe is laughable for it being in the last skills unlocked, it's a tier 1 recipe. The recipe should either reflect its tier or get moved down to the normal research bench, imo it is really not a skill that should be unlockable that late

**Comment by primo4e** [comment]
Ill take a look at it. Thats just the default as added by original modder. I can give it a bit of a change here eventually
