### ISSUE TITLE
MadScience

### ISSUE THREAD

**Issue by BoboMcFrenzy** [Storm-Veil-Gaming/Storm-Veil-Modding#25]
Issues and opinions on Madscience.
- Upgrade 2-4 take basic labor instead of madscience.
- Upgrade 2 requires culinary modern papers which can only be made after industry and electronics. Maybe move boiled sausage to kitchen instead of stove for an easy fix.
- Upgrades might need a look at the recipes overall, its just basic mats from other classes, needs some papers instead maybe.
- Culinary research paper modern Ink/Paper not affected by upgrades
- Metallurgy research paper modern Ink/Paper not affected by upgrades
- Animal Husbandry should not be in there, learned it to have a look at it, imo it should be a archaeo unlock, researcher tops. It was done 1000's of years before, doesn't require anything besides some basic food and a feeder, the real good recipes in there are gated with cutting edge cooking so it doesn't make hunting obsolete early and it requires quite a lot of food/fibers to pump out those cows. Seems quite balanced for an early skill.

So looking at it at the moment the skill is kinda lacking since you cant do much to advance the levels. It's just spamming the metal papers and those aren't needed that often. Changes to the upgrades would help there, maybe remove one of the required components and add a metal paper instead. A second unlock at level 3 would be nice to make 3 a bit more impactful. Maybe composites at 3, other option would be industry (good stuff from it would still be gated behind electronics).

**Comment by primo4e** [comment]
Ill dig into all this later today, don't have a ton of time Sunday mornings, and get all the issues you've posted so far taken care off.
